from django import forms
from .models import DataCR, PubType, PubTitle, Language, Reference, Habitat, SpeciesName
from .models import RAP, Lifestage, StudyType, Radionuclide, WildlifeGroup, Tissue

class DataCRForm(forms.ModelForm):
    # Reference section
    reference_id = forms.IntegerField(widget=forms.HiddenInput())  # Assuming this is autogenerated
    author = forms.CharField(max_length=500)
    ref_article_title = forms.ModelChoiceField(queryset=Reference.objects.all(), to_field_name='article_title')
    publication_title = forms.ModelChoiceField(queryset=PubTitle.objects.all(), to_field_name='pub_title_name')
    year = forms.CharField(max_length=30)
    volume = forms.CharField(max_length=50)
    part = forms.CharField(max_length=50)
    page_numbers = forms.CharField(max_length=50)
    reference_language = forms.ModelChoiceField(queryset=Language.objects.all(), to_field_name='language')
    publication_type = forms.ModelChoiceField(queryset=PubType.objects.all(), to_field_name='pub_type_name')
    translation_available = forms.BooleanField(required=False)
    notes = forms.CharField(max_length=500, required=False)

    # DataCR section
    measurement_date = forms.DateField()
    habitat_specific_type = forms.ModelChoiceField(queryset=Habitat.objects.all(), to_field_name='habitat_specific_type')
    icrp_rap = forms.ModelChoiceField(queryset=RAP.objects.all(), to_field_name='rap_name')
    lifestage_name = forms.ModelChoiceField(queryset=Lifestage.objects.all(), to_field_name='lifestage_name')
    wildlife_group_name = forms.ModelChoiceField(queryset=WildlifeGroup.objects.all(), to_field_name='wildlife_group_name')
    study_type_name = forms.ModelChoiceField(queryset=StudyType.objects.all(), to_field_name='study_type_name')
    name_common = forms.ModelChoiceField(queryset=SpeciesName.objects.values_list('name_common', flat=True).distinct())
    name_latin = forms.ModelChoiceField(queryset=SpeciesName.objects.values_list('name_latin', flat=True).distinct())
    radionuclide_name = forms.ModelChoiceField(queryset=Radionuclide.objects.all(), to_field_name='radionuclide_name')
    tissue_name = forms.ModelChoiceField(queryset=Tissue.objects.all(), to_field_name='tissue_name')
    media_type = forms.CharField(max_length=50)
    media_conc = forms.CharField(max_length=30)
    media_n = forms.CharField(max_length=30)
    media_conc_units = forms.CharField(max_length=20)
    media_sd = forms.CharField(max_length=30)
    media_wet_dry = forms.ChoiceField(choices=[('Wet', 'Wet'), ('Dry', 'Dry'), ('Air', 'Air')])  # Adjust choices as needed
    biota_conc = forms.CharField(max_length=30)
    biota_n = forms.CharField(max_length=30)
    biota_conc_units = forms.CharField(max_length=20)
    biota_sd = forms.CharField(max_length=30)
    biota_wet_dry = forms.ChoiceField(choices=[('Wet', 'Wet'), ('Dry', 'Dry'), ('Ash', 'Ash')])  # Adjust choices as needed
    n_of_cr = forms.IntegerField()
    concentration_ratio = forms.DecimalField(max_digits=25, decimal_places=10)
    sd_of_cr = forms.DecimalField(max_digits=25, decimal_places=10)

    class Meta:
        model = DataCR
        fields = '__all__'


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Ensure distinct values for icrp_rap, lifestage_name, and wildlife_group_name
        self.fields['icrp_rap'].queryset = RAP.objects.order_by('rap_name').distinct('rap_name')
        self.fields['lifestage_name'].queryset = Lifestage.objects.order_by('lifestage_name').distinct('lifestage_name')
        self.fields['wildlife_group_name'].queryset = WildlifeGroup.objects.order_by('wildlife_group_name').distinct('wildlife_group_name')

        # Separate querysets for common names and Latin names
        common_names = SpeciesName.objects.values_list('name_common', flat=True).distinct()
        latin_names = SpeciesName.objects.values_list('name_latin', flat=True).distinct()

        # Update the choices for each dropdown
        self.fields['name_common'].widget.choices = [(name, name) for name in common_names]
        self.fields['name_latin'].widget.choices = [(name, name) for name in latin_names]
