# Generated by Django 4.2.7 on 2023-11-14 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ClientID', models.IntegerField(primary_key=True, serialize=False)),
                ('Salutation', models.CharField(max_length=50)),
                ('Firstname', models.CharField(max_length=200)),
                ('Lastname', models.CharField(max_length=200)),
                ('EmailAddress', models.CharField(max_length=200)),
                ('JobTitle', models.CharField(max_length=200)),
                ('CompanyName', models.CharField(max_length=200)),
                ('CompanyStreet1', models.CharField(max_length=200)),
                ('CompanyStreet2', models.CharField(max_length=200)),
                ('CompanyCity', models.CharField(max_length=200)),
                ('CompanyCountry', models.CharField(max_length=200)),
                ('CompanyPostcode', models.CharField(max_length=50)),
                ('CompanyTel', models.CharField(max_length=20)),
                ('Website', models.CharField(max_length=200)),
                ('CompanyFaxno', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=50)),
                ('Password1', models.CharField(max_length=200)),
                ('AdminPriv', models.BooleanField(default=False)),
                ('MoreInfo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EditTable',
            fields=[
                ('EditID', models.IntegerField(primary_key=True, serialize=False)),
                ('TableName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('ElementID', models.IntegerField(primary_key=True, serialize=False)),
                ('Element', models.CharField(max_length=50)),
                ('Approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('HabitatID', models.IntegerField(primary_key=True, serialize=False)),
                ('Habitat', models.CharField(max_length=200)),
                ('Approved', models.BooleanField(default=False)),
                ('MainHabitatType', models.SmallIntegerField()),
                ('UserID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('LanguageID', models.IntegerField(primary_key=True, serialize=False)),
                ('Language1', models.CharField(max_length=50)),
                ('Approved', models.BooleanField(default=False)),
                ('UserID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lifestage',
            fields=[
                ('LifestageID', models.IntegerField(primary_key=True, serialize=False)),
                ('Lifestage', models.CharField(max_length=50)),
                ('Approved', models.BooleanField(default=False)),
                ('LinktoRAP', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('LocationID', models.IntegerField(primary_key=True, serialize=False)),
                ('Location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('MediaID', models.IntegerField(primary_key=True, serialize=False)),
                ('MediaType', models.CharField(max_length=50)),
                ('Approved', models.BooleanField(default=False)),
                ('UserID', models.IntegerField()),
                ('HabitatID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PubTitle',
            fields=[
                ('PubTitleID', models.IntegerField(primary_key=True, serialize=False)),
                ('PubTitle', models.CharField(max_length=200)),
                ('Approved', models.BooleanField(default=False)),
                ('UserID', models.IntegerField()),
                ('ArticleType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PubType',
            fields=[
                ('PubTypeID', models.IntegerField(primary_key=True, serialize=False)),
                ('ArticleType', models.CharField(max_length=200)),
                ('Approved', models.BooleanField(default=False)),
                ('UserID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesName',
            fields=[
                ('SpeciesID', models.IntegerField(primary_key=True, serialize=False)),
                ('NameLatin', models.CharField(max_length=200)),
                ('NameCommon', models.CharField(max_length=200)),
                ('Approved', models.BooleanField(default=False)),
                ('UserID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudyType',
            fields=[
                ('StudyTypeID', models.IntegerField(primary_key=True, serialize=False)),
                ('StudyType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tissue',
            fields=[
                ('TissueID', models.IntegerField(primary_key=True, serialize=False)),
                ('Approved', models.BooleanField(default=False)),
                ('UserID', models.IntegerField()),
                ('CorrectionFactor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Wildlife',
            fields=[
                ('WildlifeGroupNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('WildlifeGroup', models.CharField(max_length=200)),
                ('Approved', models.BooleanField(default=False)),
                ('DataExtract', models.IntegerField()),
                ('UserID', models.IntegerField()),
                ('HabitatName', models.CharField(max_length=200)),
                ('de_tophab_topwild', models.IntegerField()),
                ('de_tophab_indwild', models.IntegerField()),
                ('de_indhab_topwild', models.IntegerField()),
                ('de_indhab_indwild', models.IntegerField()),
                ('HabitatID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.habitat')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('RefID', models.IntegerField(primary_key=True, serialize=False)),
                ('Author', models.CharField(max_length=500)),
                ('ArticleTitle', models.CharField(max_length=500)),
                ('Year1', models.SmallIntegerField()),
                ('Volume', models.SmallIntegerField()),
                ('Part', models.CharField(max_length=20)),
                ('Pages', models.CharField(max_length=20)),
                ('Translation1', models.CharField(max_length=5)),
                ('Keyword1', models.CharField(max_length=50)),
                ('Keyword2', models.CharField(max_length=50)),
                ('Keyword3', models.CharField(max_length=50)),
                ('Keyword4', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=200)),
                ('Notes', models.CharField(max_length=500)),
                ('UserID', models.IntegerField()),
                ('DC_ID', models.IntegerField()),
                ('ApprovalStatus', models.CharField(max_length=20)),
                ('ReasonApprovalDelete', models.CharField(max_length=500)),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.language')),
                ('PubTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.pubtitle')),
                ('PubType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.pubtype')),
            ],
        ),
        migrations.CreateModel(
            name='RAP',
            fields=[
                ('RAP_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('RAP', models.CharField(max_length=200)),
                ('Approved', models.BooleanField(default=False)),
                ('Summary', models.CharField(max_length=200)),
                ('HabitatID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.habitat')),
                ('WildlifeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.wildlife')),
            ],
        ),
        migrations.CreateModel(
            name='Radionuclide',
            fields=[
                ('RadionuclideNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('Radionuclide', models.CharField(max_length=50)),
                ('Approved', models.BooleanField(default=False)),
                ('UserID', models.IntegerField()),
                ('Element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.element')),
            ],
        ),
        migrations.CreateModel(
            name='ParCRCalc',
            fields=[
                ('CF_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('WetDryRatio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('AshRatio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('IsFreMarTer', models.CharField(choices=[('F', 'Freshwater'), ('M', 'Marine'), ('T', 'Terrestrial')], max_length=1)),
                ('Tissue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.tissue')),
                ('WildlifeGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.wildlife')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialStatus',
            fields=[
                ('MaterialStatusID', models.IntegerField(primary_key=True, serialize=False)),
                ('MaterialStatus', models.CharField(max_length=50)),
                ('CorrectionRatio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('MediaTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.media')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialCRCalc',
            fields=[
                ('CF_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Organism', models.CharField(max_length=50)),
                ('Liver', models.CharField(max_length=50)),
                ('Bone', models.CharField(max_length=50)),
                ('Muscle', models.CharField(max_length=50)),
                ('IsFreMarTer', models.CharField(choices=[('F', 'Freshwater'), ('M', 'Marine'), ('T', 'Terrestrial')], max_length=1)),
                ('Element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.element')),
            ],
        ),
        migrations.CreateModel(
            name='DataCR',
            fields=[
                ('CR_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Wildlife', models.CharField(max_length=200)),
                ('ICRPRAP', models.CharField(max_length=200)),
                ('Lifestage', models.CharField(max_length=200)),
                ('MeasurementDate', models.DateField()),
                ('CRN', models.SmallIntegerField()),
                ('CR', models.IntegerField()),
                ('CR_SD', models.IntegerField()),
                ('Notes', models.CharField(max_length=500)),
                ('FromERICA', models.BooleanField(default=False)),
                ('Accepted', models.BooleanField(default=False)),
                ('Biohalflife', models.CharField(max_length=30)),
                ('BiotaConc', models.CharField(max_length=30)),
                ('BiotaConcUnits', models.CharField(max_length=30)),
                ('BiotaN', models.CharField(max_length=30)),
                ('BiotaSD', models.CharField(max_length=30)),
                ('BiotaWetDry', models.CharField(max_length=30)),
                ('DataExtract', models.IntegerField()),
                ('Location', models.CharField(max_length=30)),
                ('MediaConc', models.CharField(max_length=30)),
                ('MediaN', models.CharField(max_length=30)),
                ('MediaConcUnits', models.CharField(max_length=30)),
                ('MediaSD', models.CharField(max_length=30)),
                ('MediaWetDry', models.CharField(max_length=30)),
                ('OtherTissue', models.BooleanField(default=False)),
                ('QC', models.CharField(max_length=30)),
                ('RepOrganUnits', models.CharField(max_length=30)),
                ('ReproductiveOrgan', models.CharField(max_length=30)),
                ('RepWetDry', models.CharField(max_length=30)),
                ('StandBiotaConc', models.CharField(max_length=30)),
                ('StandBiotaSD', models.CharField(max_length=30)),
                ('StandMediaConc', models.CharField(max_length=30)),
                ('StandMediaSD', models.CharField(max_length=30)),
                ('SummaryApprove', models.BooleanField(default=False)),
                ('ApprovalDataStatus', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('HabitatID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.habitat')),
                ('Media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.media')),
                ('Radionuclide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.radionuclide')),
                ('RefID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.reference')),
                ('SpNameLatin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.speciesname')),
                ('StudyType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.studytype')),
                ('Tissue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.tissue')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityConcentrationUnit',
            fields=[
                ('ActivityConcUnitID', models.AutoField(primary_key=True, serialize=False)),
                ('ActConcUnits', models.CharField(max_length=50)),
                ('Approved', models.BooleanField(default=False)),
                ('CorrectionFactor', models.DecimalField(decimal_places=3, max_digits=10)),
                ('UnitNumber', models.SmallIntegerField()),
                ('MediaTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_app.media')),
            ],
        ),
    ]
