# Generated by Django 5.0.1 on 2024-01-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_priv',
            field=models.SmallIntegerField(null=True),
        ),
    ]
