# Generated by Django 5.0 on 2023-12-14 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0002_activityconcunit_wildlifegroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='language_1',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='radionuclide',
            old_name='radionuclide_number',
            new_name='radionuclide_id',
        ),
        migrations.RenameField(
            model_name='radionuclide',
            old_name='nuclide_name',
            new_name='radionuclide_name',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='Notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='year_1',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='language',
            name='user_id',
        ),
        migrations.AddField(
            model_name='language',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
