# Generated by Django 5.0 on 2023-12-15 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0003_rename_language_1_language_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacr',
            name='habitat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.habitat'),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='icrp_rap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.rap'),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='lifestage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.lifestage'),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.media'),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='radionuclide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.radionuclide'),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.reference'),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='species_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.speciesname'),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='study_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.studytype'),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='tissue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.tissue'),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='wildlife_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.wildlifegroup'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='article_title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.language'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='pub_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.pubtype'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
