# Generated by Django 5.0 on 2023-12-15 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0004_alter_datacr_habitat_alter_datacr_icrp_rap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='pub_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.pubtitle'),
        ),
    ]
