# Generated by Django 5.0.1 on 2024-01-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0004_alter_parcrcalc_ash_to_wet_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcrcalc',
            name='dry_to_wet_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
