# Generated by Django 5.0.1 on 2024-01-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0005_alter_parcrcalc_dry_to_wet_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcrcalc',
            name='bone_to_body_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='materialcrcalc',
            name='liver_to_body_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='materialcrcalc',
            name='muscle_to_body_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
