# Generated by Django 5.0 on 2023-12-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0005_alter_reference_pub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='volume',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
