# Generated by Django 5.0.1 on 2024-01-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0006_alter_materialcrcalc_bone_to_body_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_priv',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
