# Generated by Django 5.0 on 2023-12-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0006_alter_reference_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
