# Generated by Django 5.0.1 on 2024-01-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0007_alter_user_admin_priv'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissue',
            name='tissue_name',
            field=models.CharField(default='Default', max_length=50),
        ),
    ]
