# Generated by Django 5.0 on 2023-12-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0007_alter_reference_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='keyword_1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='reference',
            name='keyword_2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='reference',
            name='keyword_3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='reference',
            name='keyword_4',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='reference',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='reference',
            name='pages',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='reference',
            name='part',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reason_approval_delete',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='reference',
            name='translation',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='reference',
            name='volume',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
