# Generated by Django 5.0 on 2023-12-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0008_alter_reference_keyword_1_alter_reference_keyword_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='year',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
