# Generated by Django 5.0.1 on 2024-01-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0008_tissue_tissue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacr',
            name='biota_conc_units',
            field=models.CharField(blank=True, choices=[('µCi/kg', 'µCi/kg'), ('Bq/kg', 'Bq/kg'), ('Bg/kg fresh', 'Bg/kg fresh'), ('Bg/kg FW', 'Bg/kg FW'), ('Bq/l', 'Bq/l'), ('mg/kg fresh', 'mg/kg fresh'), ('mg/kg', 'mg/kg'), ('mg/kg FW', 'mg/kg FW'), ('Bq/m3', 'Bq/m3'), ('mBq/l', 'mBq/l'), ('mg/l', 'mg/l'), ('p/Ci/l', 'p/Ci/l'), ('ppb', 'ppb'), ('ppm', 'ppm'), ('uCi/l', 'uCi/l')], default='Bq/kg', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='media_conc_units',
            field=models.CharField(blank=True, choices=[('µCi/kg', 'µCi/kg'), ('Bq/g', 'Bq/g'), ('Bq/m2', 'Bq/m2'), ('mBq/g', 'mBq/g'), ('mBq/kg', 'mBq/kg'), ('mg/g', 'mg/g'), ('mg/kg', 'mg/kg'), ('pCi/g', 'pCi/g'), ('pCi/kg', 'pCi/kg'), ('ppb', 'ppb'), ('ppm', 'ppm'), ('ug/g', 'ug/g'), ('ug/kg', 'ug/kg')], default='Bq/kg', max_length=20, null=True),
        ),
    ]
