# Generated by Django 5.0 on 2023-12-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0009_alter_reference_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='pages',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='reference',
            name='part',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='reference',
            name='volume',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='reference',
            name='year',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
