# Generated by Django 5.0.1 on 2024-01-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0009_alter_datacr_biota_conc_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacr',
            name='media_wet_dry',
            field=models.CharField(blank=True, choices=[('W', 'Wet'), ('D', 'Dry'), ('A', 'Air')], default='W', max_length=10, null=True),
        ),
    ]
