# Generated by Django 5.0 on 2023-12-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0010_alter_reference_pages_alter_reference_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacr',
            name='biohalflife',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='biota_conc',
            field=models.DecimalField(decimal_places=15, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='biota_conc_units',
            field=models.CharField(blank=True, choices=[('µCi/kg', 'µCi/kg'), ('Bq/kg', 'Bq/kg'), ('Bg/kg fresh', 'Bg/kg fresh'), ('Bg/kg FW', 'Bg/kg FW'), ('Bq/l', 'Bq/l'), ('mg/kg fresh', 'mg/kg fresh'), ('bg/kg FW', 'bg/kg FW')], default='Bq/kg', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='biota_n',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='biota_sd',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='biota_wet_dry',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='cr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='cr_sd',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='crn',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='data_extract',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='measurement_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='media_conc',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='media_conc_units',
            field=models.CharField(blank=True, choices=[('Bq/kg', 'Bq/kg'), ('Bq/l', 'Bq/l'), ('mBq/l', 'mBq/l')], default='Bq/kg', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='media_n',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='media_sd',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='media_wet_dry',
            field=models.CharField(blank=True, choices=[('W', 'Wet'), ('D', 'Dry')], default='W', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='notes',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='qc',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='rep_organ_units',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='rep_wet_dry',
            field=models.CharField(blank=True, choices=[('W', 'Wet'), ('D', 'Dry')], default='W', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='reproductive_organ',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='stand_biota_conc',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='stand_biota_sd',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='stand_media_conc',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='stand_media_sd',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
