# Generated by Django 5.0.1 on 2024-01-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0010_alter_datacr_media_wet_dry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacr',
            name='cr_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
