# Generated by Django 5.0 on 2023-12-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0011_alter_datacr_biohalflife_alter_datacr_biota_conc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacr',
            name='measurement_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
