# Generated by Django 5.0.1 on 2024-01-24 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0011_alter_datacr_cr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacr',
            name='approval_data_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='biohalflife',
            field=models.CharField(blank=True, default='Default Biohalflife', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='biota_conc',
            field=models.CharField(blank=True, default='Default Biota Conc', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='biota_n',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='biota_sd',
            field=models.CharField(blank=True, default='Default Biota SD', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='cr',
            field=models.DecimalField(blank=True, decimal_places=10, default=1.0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='cr_sd',
            field=models.DecimalField(blank=True, decimal_places=10, default=1.0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='crn',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='data_extract',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='habitat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.habitat'),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='icrp_rap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.rap'),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='lifestage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.lifestage'),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='measurement_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.media'),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='media_conc',
            field=models.CharField(blank=True, default='Default Media Conc', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='media_n',
            field=models.CharField(blank=True, default='Default Media N', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='media_sd',
            field=models.CharField(blank=True, default='Default Media SD', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='other_tissue',
            field=models.CharField(blank=True, default='Default Other Tissue', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='radionuclide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.radionuclide'),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.reference'),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='rep_organ_units',
            field=models.CharField(blank=True, default='Default Rep Organ Units', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='reproductive_organ',
            field=models.CharField(blank=True, default='Default Reproductive Organ', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='species_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.speciesname'),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='stand_biota_conc',
            field=models.DecimalField(blank=True, decimal_places=3, default=1.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='stand_biota_sd',
            field=models.CharField(blank=True, default='Default Stand Biota SD', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='stand_media_conc',
            field=models.DecimalField(blank=True, decimal_places=3, default=1.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='stand_media_sd',
            field=models.CharField(blank=True, default='Default Stand Media SD', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='study_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.studytype'),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='tissue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.tissue'),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='wildlife_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_app.wildlifegroup'),
        ),
    ]
