# Generated by Django 5.0 on 2023-12-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0012_alter_datacr_measurement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacr',
            name='other_tissue',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='qc',
            field=models.BooleanField(default=False),
        ),
    ]
