# Generated by Django 5.0.1 on 2024-01-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0012_alter_datacr_approval_data_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacr',
            name='biota_wet_dry',
            field=models.CharField(blank=True, choices=[('Water', 'Water'), ('Dry', 'Dry'), ('Air', 'Air'), ('Soil', 'Soil')], default='Dry', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='media_conc_units',
            field=models.CharField(blank=True, choices=[('µCi/kg', 'µCi/kg'), ('Bq/g', 'Bq/g'), ('Bq/kg', 'Bq/kg'), ('Bq/m2', 'Bq/m2'), ('mBq/g', 'mBq/g'), ('mBq/kg', 'mBq/kg'), ('mg/g', 'mg/g'), ('mg/kg', 'mg/kg'), ('pCi/g', 'pCi/g'), ('pCi/kg', 'pCi/kg'), ('ppb', 'ppb'), ('ppm', 'ppm'), ('ug/g', 'ug/g'), ('ug/kg', 'ug/kg')], default='Bq/kg', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='media_wet_dry',
            field=models.CharField(blank=True, choices=[('Water', 'Water'), ('Dry', 'Dry'), ('Air', 'Air'), ('Soil', 'Soil')], default='Dry', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='rep_wet_dry',
            field=models.CharField(blank=True, choices=[('Water', 'Water'), ('Dry', 'Dry'), ('Air', 'Air'), ('Soil', 'Soil')], default='Dry', max_length=5, null=True),
        ),
    ]
