# Generated by Django 5.0 on 2023-12-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0013_alter_datacr_other_tissue_alter_datacr_qc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacr',
            name='biota_conc',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
