# Generated by Django 5.0.1 on 2024-01-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0014_alter_datacr_biota_wet_dry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='ref_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
