# Generated by Django 5.0 on 2023-12-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0014_alter_datacr_biota_conc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacr',
            name='media_conc',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
