# Generated by Django 5.0.1 on 2024-01-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0015_alter_reference_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='dc_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
