# Generated by Django 5.0 on 2023-12-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0015_alter_datacr_media_conc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacr',
            name='qc',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
