# Generated by Django 5.0.1 on 2024-01-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0016_alter_reference_dc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='ref_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
