# Generated by Django 5.0 on 2023-12-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0016_alter_datacr_qc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacr',
            name='qc',
            field=models.BooleanField(default=False),
        ),
    ]
