# Generated by Django 5.0 on 2023-12-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0017_alter_datacr_qc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacr',
            name='crn',
            field=models.IntegerField(null=True),
        ),
    ]
