# Generated by Django 5.0 on 2023-12-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0018_alter_datacr_crn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacr',
            name='media_wet_dry',
            field=models.CharField(blank=True, choices=[('W', 'Wet'), ('D', 'Dry')], default='W', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='rep_wet_dry',
            field=models.CharField(blank=True, choices=[('W', 'Wet'), ('D', 'Dry')], default='W', max_length=5, null=True),
        ),
    ]
