# Generated by Django 5.0.1 on 2024-02-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0018_alter_reference_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacr',
            name='biota_wet_dry',
            field=models.CharField(blank=True, choices=[('Water', 'Water'), ('Wet', 'Wet'), ('Dry', 'Dry'), ('Air', 'Air'), ('Soil', 'Soil'), ('undefined', 'undefined')], default='Dry', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='media_wet_dry',
            field=models.CharField(blank=True, choices=[('Water', 'Water'), ('Wet', 'Wet'), ('Dry', 'Dry'), ('Air', 'Air'), ('Soil', 'Soil'), ('undefined', 'undefined')], default='Dry', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='rep_wet_dry',
            field=models.CharField(blank=True, choices=[('Water', 'Water'), ('Wet', 'Wet'), ('Dry', 'Dry'), ('Air', 'Air'), ('Soil', 'Soil'), ('undefined', 'undefined')], default='Dry', max_length=10, null=True),
        ),
    ]
