# Generated by Django 5.0.1 on 2024-02-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0019_alter_datacr_biota_wet_dry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacr',
            name='cr',
            field=models.DecimalField(decimal_places=10, max_digits=25, null=True),
        ),
    ]
