# Generated by Django 5.0.1 on 2024-02-09 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0020_alter_datacr_cr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='dc_id',
        ),
    ]
