# Generated by Django 5.0 on 2023-12-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0020_alter_datacr_media_wet_dry_alter_datacr_rep_wet_dry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacr',
            name='biota_conc_units',
            field=models.CharField(blank=True, choices=[('µCi/kg', 'µCi/kg'), ('Bq/kg', 'Bq/kg'), ('Bg/kg fresh', 'Bg/kg fresh'), ('Bg/kg FW', 'Bg/kg FW'), ('Bq/l', 'Bq/l'), ('mg/kg fresh', 'mg/kg fresh'), ('mg/kg', 'mg/kg'), ('bg/kg FW', 'bg/kg FW'), ('Bq/m3', 'Bq/m3')], default='Bq/kg', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='media_conc_units',
            field=models.CharField(blank=True, choices=[('Bq/kg', 'Bq/kg'), ('Bq/l', 'Bq/l'), ('Bq/m3', 'Bq/m3'), ('mBq/l', 'mBq/l'), ('mg/kg', 'mg/kg')], default='Bq/kg', max_length=20, null=True),
        ),
    ]
