# Generated by Django 5.0 on 2023-12-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0021_alter_datacr_biota_conc_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacr',
            name='biota_conc_units',
            field=models.CharField(blank=True, choices=[('µCi/kg', 'µCi/kg'), ('Bq/kg', 'Bq/kg'), ('Bg/kg fresh', 'Bg/kg fresh'), ('Bg/kg FW', 'Bg/kg FW'), ('Bq/l', 'Bq/l'), ('mg/kg fresh', 'mg/kg fresh'), ('mg/kg', 'mg/kg'), ('mg/kg FW', 'mg/kg FW'), ('Bq/m3', 'Bq/m3')], default='Bq/kg', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='biota_wet_dry',
            field=models.CharField(blank=True, choices=[('W', 'Wet'), ('D', 'Dry'), ('A', 'Air')], default='W', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='cr',
            field=models.DecimalField(decimal_places=10, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='cr_sd',
            field=models.DecimalField(decimal_places=10, max_digits=25, null=True),
        ),
    ]
