# Generated by Django 5.0.1 on 2024-02-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0022_remove_reference_keyword_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacr',
            name='from_erica',
        ),
    ]
