# Generated by Django 5.0.1 on 2024-02-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0023_remove_datacr_from_erica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacr',
            name='biohalflife',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='biota_conc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='biota_conc_units',
            field=models.CharField(blank=True, choices=[('µCi/kg', 'µCi/kg'), ('Bq/kg', 'Bq/kg'), ('Bg/kg fresh', 'Bg/kg fresh'), ('Bg/kg FW', 'Bg/kg FW'), ('Bq/l', 'Bq/l'), ('mg/kg fresh', 'mg/kg fresh'), ('mg/kg', 'mg/kg'), ('mg/kg FW', 'mg/kg FW'), ('Bq/m3', 'Bq/m3'), ('mBq/l', 'mBq/l'), ('mg/l', 'mg/l'), ('p/Ci/l', 'p/Ci/l'), ('ppb', 'ppb'), ('ppm', 'ppm'), ('uCi/l', 'uCi/l')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='biota_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='biota_sd',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='biota_wet_dry',
            field=models.CharField(blank=True, choices=[('Water', 'Water'), ('Wet', 'Wet'), ('Dry', 'Dry'), ('Air', 'Air'), ('Soil', 'Soil'), ('undefined', 'undefined')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='cr_sd',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='crn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='data_extract',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='media_conc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='media_conc_units',
            field=models.CharField(blank=True, choices=[('µCi/kg', 'µCi/kg'), ('Bq/g', 'Bq/g'), ('Bq/kg', 'Bq/kg'), ('Bq/m2', 'Bq/m2'), ('mBq/g', 'mBq/g'), ('mBq/kg', 'mBq/kg'), ('mg/g', 'mg/g'), ('mg/kg', 'mg/kg'), ('pCi/g', 'pCi/g'), ('pCi/kg', 'pCi/kg'), ('ppb', 'ppb'), ('ppm', 'ppm'), ('ug/g', 'ug/g'), ('ug/kg', 'ug/kg')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='media_n',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='media_sd',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='media_wet_dry',
            field=models.CharField(blank=True, choices=[('Water', 'Water'), ('Wet', 'Wet'), ('Dry', 'Dry'), ('Air', 'Air'), ('Soil', 'Soil'), ('undefined', 'undefined')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='other_tissue',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='rep_organ_units',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='rep_wet_dry',
            field=models.CharField(blank=True, choices=[('Water', 'Water'), ('Wet', 'Wet'), ('Dry', 'Dry'), ('Air', 'Air'), ('Soil', 'Soil'), ('undefined', 'undefined')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='reproductive_organ',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='stand_biota_conc',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='stand_biota_sd',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='stand_media_conc',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='stand_media_sd',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='reference',
            name='pages',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reference',
            name='part',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reason_approval_delete',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='reference',
            name='translation',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='reference',
            name='volume',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reference',
            name='year',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='tissue',
            name='tissue_name',
            field=models.CharField(max_length=50),
        ),
    ]
