# Generated by Django 5.0.1 on 2024-02-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0024_alter_datacr_biohalflife_alter_datacr_biota_conc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='author',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='pages',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='part',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reason_approval_delete',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='volume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='year',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
