# Generated by Django 5.0.1 on 2024-02-11 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0025_alter_reference_author_alter_reference_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datacr',
            old_name='approval_data_status',
            new_name='approval_status',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='reason_approval_delete',
        ),
        migrations.CreateModel(
            name='ReferenceRejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('reference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_reason', to='data_app.reference')),
            ],
        ),
    ]
