# Generated by Django 5.0.1 on 2024-02-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0026_rename_approval_data_status_datacr_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='datacr',
            name='biota_conc_units',
            field=models.CharField(blank=True, choices=[('µCi/kg', 'µCi/kg'), ('Bq/g', 'Bq/g'), ('Bq/kg', 'Bq/kg'), ('Bq/l', 'Bq/l'), ('Bq/m2', 'Bq/m2'), ('Bq/m3', 'Bq/m3'), ('mBq/g', 'mBq/g'), ('mBq/kg', 'mBq/kg'), ('mBq/l', 'mBq/l'), ('mg/g', 'mg/g'), ('mg/kg', 'mg/kg'), ('mg/l', 'mg/l'), ('pCi/g', 'pCi/g'), ('pCi/kg', 'pCi/kg'), ('pCi/l', 'pCi/l'), ('ppb', 'ppb'), ('ppm', 'ppm'), ('uCi/l', 'uCi/l'), ('ug/g', 'ug/g'), ('ug/kg', 'ug/kg'), ('ug/l', 'ug/l')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='media_conc_units',
            field=models.CharField(blank=True, choices=[('µCi/kg', 'µCi/kg'), ('Bq/g', 'Bq/g'), ('Bq/kg', 'Bq/kg'), ('Bq/l', 'Bq/l'), ('Bq/m2', 'Bq/m2'), ('Bq/m3', 'Bq/m3'), ('mBq/g', 'mBq/g'), ('mBq/kg', 'mBq/kg'), ('mBq/l', 'mBq/l'), ('mg/g', 'mg/g'), ('mg/kg', 'mg/kg'), ('mg/l', 'mg/l'), ('pCi/g', 'pCi/g'), ('pCi/kg', 'pCi/kg'), ('pCi/l', 'pCi/l'), ('ppb', 'ppb'), ('ppm', 'ppm'), ('uCi/l', 'uCi/l'), ('ug/g', 'ug/g'), ('ug/kg', 'ug/kg'), ('ug/l', 'ug/l')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
