# Generated by Django 5.0.1 on 2024-03-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0028_rename_company_user_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='ref_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
