# Generated by Django 5.0.1 on 2024-03-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0029_alter_reference_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='translation',
            field=models.BooleanField(default=False),
        ),
    ]
