# Generated by Django 5.0.1 on 2024-04-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0030_alter_reference_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacr',
            name='cr_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='measurement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
