# Generated by Django 5.0.1 on 2024-04-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0031_alter_datacr_cr_id_alter_datacr_measurement_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacr',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='datacr',
            name='data_extract',
        ),
        migrations.RemoveField(
            model_name='datacr',
            name='other_tissue',
        ),
        migrations.RemoveField(
            model_name='datacr',
            name='qc',
        ),
        migrations.RemoveField(
            model_name='datacr',
            name='summary_approve',
        ),
    ]
