# Generated by Django 5.0.1 on 2024-04-24 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0032_remove_datacr_accepted_remove_datacr_data_extract_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datacr',
            old_name='crn',
            new_name='cr_n',
        ),
    ]
