# Generated by Django 5.0.1 on 2024-04-26 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0033_rename_crn_datacr_cr_n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacr',
            name='rep_organ_units',
        ),
        migrations.RemoveField(
            model_name='datacr',
            name='rep_wet_dry',
        ),
        migrations.RemoveField(
            model_name='datacr',
            name='reproductive_organ',
        ),
    ]
