# Generated by Django 5.0.1 on 2024-04-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0034_remove_datacr_rep_organ_units_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacr',
            name='stand_biota_sd',
        ),
        migrations.RemoveField(
            model_name='datacr',
            name='stand_media_sd',
        ),
        migrations.AlterField(
            model_name='datacr',
            name='stand_biota_conc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacr',
            name='stand_media_conc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
