# Generated by Django 5.0.1 on 2024-05-01 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0035_remove_datacr_stand_biota_sd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='jobtitle',
            new_name='job_title',
        ),
    ]
