# Generated by Django 5.0.1 on 2024-05-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0036_rename_jobtitle_user_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
